"""Migration 25_12_2024

Revision ID: 5b41a68a9f0a
Revises: 6b18eb1e0dc6
Create Date: 2024-12-25 15:00:33.488106

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5b41a68a9f0a"
down_revision: Union[str, None] = "6b18eb1e0dc6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "categories", "description", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.alter_column(
        "menu_items", "description", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.alter_column(
        "menu_items", "image_url", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.alter_column(
        "order_items", "notes", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.alter_column(
        "ratings", "comment", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.alter_column(
        "roles", "description", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "roles", "description", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.alter_column(
        "ratings", "comment", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.alter_column(
        "order_items", "notes", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.alter_column(
        "menu_items", "image_url", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.alter_column(
        "menu_items",
        "description",
        existing_type=sa.VARCHAR(length=255),
        nullable=False,
    )
    op.alter_column(
        "categories",
        "description",
        existing_type=sa.VARCHAR(length=255),
        nullable=False,
    )
    # ### end Alembic commands ###
