"""Migration 06_12_2024

Revision ID: 64c9bd259c71
Revises: ca2af0ba3c47
Create Date: 2024-12-06 20:47:12.860860

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "64c9bd259c71"
down_revision: Union[str, None] = "ca2af0ba3c47"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "restaurants",
        "status",
        existing_type=sa.VARCHAR(length=25),
        type_=sa.Enum("OPEN", "CLOSE", name="restaurantstatusenum", native_enum=False),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "restaurants",
        "status",
        existing_type=sa.Enum(
            "OPEN", "CLOSE", name="restaurantstatusenum", native_enum=False
        ),
        type_=sa.VARCHAR(length=25),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
