"""Migration 06_12_2024

Revision ID: ca2af0ba3c47
Revises: 74a0d3c454b6
Create Date: 2024-12-06 20:33:10.169803

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ca2af0ba3c47"
down_revision: Union[str, None] = "74a0d3c454b6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "restaurants",
        "rating",
        existing_type=sa.NUMERIC(precision=3, scale=2),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "restaurants",
        "rating",
        existing_type=sa.NUMERIC(precision=3, scale=2),
        nullable=False,
    )
    # ### end Alembic commands ###
